baseURL = "https://kduy-hi.github.io/internship-report_Kh-nh-Duy/"
relativeURLs = false
canonifyURLs = false
defaultContentLanguage = "vi"

theme = "hugo-theme-learn"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  themeVariant = "workshop"
  editURL = ""
  description = "Bao cao thuc tap ve du an Cloud-based Student Internship Portal on AWS"
  author = "Nguyen Van A"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false

[Languages]
[Languages.vi]
title = "Bao cao thuc tap"
weight = 1
label = "Tieng Viet"

[[Languages.vi.menu.shortcuts]]
name = "<i class='fab fa-aws'></i> AWS Study Group - Blog"
identifier = "AWS Study Group"
url = "https://awsstudygroup.com"
weight = 20

[[Languages.vi.menu.shortcuts]]
name = "<i class='fab fa-facebook'></i> AWS Study Group - Nhom FB"
identifier = "AWS Study Group FB"
url = "https://www.facebook.com/groups/awsstudygroupfcj"
weight = 20

[Languages.en]
title = "Internship Report"
weight = 2
label = "English"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-aws'></i> AWS Study Group - Blog"
identifier = "AWS Study Group"
url = "https://awsstudygroup.com"
weight = 20

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-facebook'></i> AWS Study Group - FB Group"
identifier = "AWS Study Group FB"
url = "https://www.facebook.com/groups/awsstudygroupfcj"
weight = 20

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
